name: chitchat
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  go_router: ^14.2.0
  image_picker: ^1.1.2
  injectable: ^2.4.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  web_socket_channel: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
